#!/bin/sh

load_bridge_runtime_env() {
  bridge_script_dir="$1"
  if [ -z "$bridge_script_dir" ]; then
    echo "load_bridge_runtime_env: script dir is required" >&2
    return 1
  fi

  if [ -f "$bridge_script_dir/.env" ]; then
    # shellcheck disable=SC1090
    . "$bridge_script_dir/.env"
  fi

  export BRIDGE_BIND BRIDGE_HOST BRIDGE_PORT HOST PORT
  set -- $(python3 "$bridge_script_dir/bridge_runtime_config.py" --print-host-port) || return 1
  HOST="$1"
  PORT="$2"
  export HOST PORT BRIDGE_BIND BRIDGE_HOST BRIDGE_PORT
}

export_bridge_runtime_env() {
  export HOST PORT BRIDGE_TOKEN BRIDGE_BASIC_AUTH WORK_DIR MAX_JSON_BODY MAX_UPLOAD_SIZE FILE_SEND_ROOTS
  export BRIDGE_BIND BRIDGE_HOST BRIDGE_PORT
  export BRIDGE_SHARED_RUNTIME_ROOT
  export BRIDGE_RUNTIME_ROOT
  export MAX_INBOUND_IMAGE_SIZE MAX_INBOUND_FILE_SIZE
  export SESSION_LEASE_TTL HTTP_PROXY HTTPS_PROXY NO_PROXY
  export MEDIA_CONNECT_TIMEOUT MEDIA_TOTAL_TIMEOUT LOCAL_FILE_SEND_QUEUE_ROOT LOCAL_FILE_SEND_POLL_MS
  export LOCAL_FILE_SEND_RESULT_TIMEOUT_MS LOCAL_FILE_SEND_RESULT_RETENTION_MS
  export LOCAL_SEND_MESSAGE_QUEUE_ROOT LOCAL_SEND_MESSAGE_RESULT_TIMEOUT_MS LOCAL_SEND_MESSAGE_RESULT_RETENTION_MS
  export CODEX_EXEC_MODE MAX_CONCURRENT_CODEX_RUNS
  export SUBPROCESS_STREAM_LIMIT SUBPROCESS_STREAM_READ_SIZE SUBPROCESS_STREAM_MAX_LINE
  export WEBSOCKET_SEND_TIMEOUT_SEC STATUS_STREAM_INTERVAL_SEC STATUS_SEND_TIMEOUT_SEC STATUS_SEND_LOCK_TIMEOUT_SEC
  export REPLY_IDLE_FALLBACK_SEC REPLY_MAX_AGE_FALLBACK_SEC PROACTIVE_STATUS_INTERVAL_SEC
  export SCHEDULE_POLL_MS
  export SCHEDULE_DEFINITION_POLL_MS SCHEDULE_DEFINITION_LEASE_TTL_MS
  export PROACTIVE_SEND_ACK_TIMEOUT_SEC
  export PROACTIVE_TEXT_MAX_CHARS
  export SCHEDULE_PROCESSING_RETRY_MS
  export SCHEDULE_ORPHAN_TTL_MS
  export BOTS_FILE WECOM_BOOTSTRAP_BOTS_JSON WECOM_BOOTSTRAP_BOTS_JSON_FILE
  export WECOM_BOT_CONFIG_ID WECOM_BOT_NAME WECOM_BOT_ID WECOM_BOT_SECRET_FILE
  export WECOM_BOT_WORK_DIR WECOM_BOT_WELCOME WECOM_BOT_GROUP_SESSION_MODE WECOM_BOT_ENABLED
  export BRIDGE_WATCHDOG_ENABLED BRIDGE_WATCHDOG_POLL_SEC BRIDGE_WATCHDOG_HEALTH_TIMEOUT_SEC
  export BRIDGE_WATCHDOG_STARTUP_GRACE_SEC BRIDGE_WATCHDOG_FAIL_THRESHOLD
  export BRIDGE_WATCHDOG_RESTART_BACKOFF_SEC BRIDGE_WATCHDOG_RESTART_WINDOW_SEC
  export BRIDGE_WATCHDOG_MAX_RESTART_STREAK BRIDGE_WATCHDOG_COOLDOWN_SEC
}
